### ISSUE TITLE
Feature 1: User can generate a random Bible verse.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/ajax-project#1]
## 📐 Functionality

> ##### Users can generate a random Bible verse to them with a click of a button.

## 🖼️ Wireframes
![User can generate a random Bible verse - mobile](https://user-images.githubusercontent.com/97268025/156259819-699c78fa-7e86-4bbd-a98b-e0524aa588e7.png)

![User can generate a random Bible verse - desktop](https://user-images.githubusercontent.com/97268025/156259831-88ed1390-8fd8-4f7c-97de-34658dab5317.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML skeleton for the home page.
- [x] Input text content for the header, body and the footer.
- [x] Set the background image with text on top for the home page.
- [x] Create a button.
- [x] Apply CSS rule sets to the appropriate elements, classes & IDs.
- [x] Ensure that the page looks nice on both mobile & desktop.
- [x] Create a data model.
- [x] Add an event listener to the button to listen for clicks.
- [x] Ensure that everything but the button and verse is hidden when the button is clicked using the data model.
- [x] Ensure that a new verse is being generated every-time the 'New Verse' button is clicked.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
