### ISSUE TITLE
Feature 3: User can save Bible verses.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/ajax-project#3]
## 📐 Functionality

> ##### Users can save Bible verses that were generated or that they searched for.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add save buttons onto the 'generate' page when a verse pops up.
- [x] Create journal entries page.
- [x] Ensure that when a user clicks that save button, the verse is populate into the journal entries page.
- [x] Make sure the verse is being saved onto the data model.
- [x] Style the journal entries.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
