### ISSUE TITLE
Feature 4: User can journal about the verses they saved.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/ajax-project#4]
## 📐 Functionality

> ##### User can journal about the verses that they saved.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create edit page/modal that allows users to write journal entries.
- [x] Add a new button next to saved verses.
- [x] Ensure that when the new button is clicked, the edit page/modal appears.
- [x] Once a user has written their entry, save that entry into the data model.
- [x] Ensure that the entry pops up next to the saved verses when saved.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
