### ISSUE TITLE
Feature 5: User can edit their journal entries.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/ajax-project#5]
## 📐 Functionality

> ##### Users can edit their journal entries and save them again.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Allow users to edit their saved entry without the previous entry being deleted from the text box.
- [x] Ensure that when a user looks to edit their saved entry, the correct corresponding verse is being populated.
- [x] Utilize local storage to make sure the verses and entries are being properly saved.
- [x] Add styling to the edit-page.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
